### ISSUE TITLE
error in compiling ui

### ISSUE THREAD

**Issue by resource11** [CLIxIndia-Dev/unplatform_v2#25]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/kathleenmcmahon/.virtualenvs/venv/bin/node',
1 verbose cli   '/Users/kathleenmcmahon/.virtualenvs/venv/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile:ui' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'precompile:ui', 'compile:ui', 'postcompile:ui' ]
5 info lifecycle Unplatform-V2@1.2.0~precompile:ui: Unplatform-V2@1.2.0
6 silly lifecycle Unplatform-V2@1.2.0~precompile:ui: no script for precompile:ui, continuing
7 info lifecycle Unplatform-V2@1.2.0~compile:ui: Unplatform-V2@1.2.0
8 verbose lifecycle Unplatform-V2@1.2.0~compile:ui: unsafe-perm in lifecycle true
9 verbose lifecycle Unplatform-V2@1.2.0~compile:ui: PATH: /Users/kathleenmcmahon/.virtualenvs/venv/lib/node_modules/npm/bin/node-gyp-bin:/Users/kathleenmcmahon/MIT_projects/unplatform_v2/node_modules/.bin:/Users/kathleenmcmahon/.virtualenvs/venv/bin:/Users/kathleenmcmahon/.nvm/versions/node/v6.9.4/bin:/usr/local/Cellar/pyenv-virtualenv/20160315/shims:/usr/local/var/pyenv/shims:/usr/local/var/rbenv/shims:/Users/kathleenmcmahon/.rbenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle Unplatform-V2@1.2.0~compile:ui: CWD: /Users/kathleenmcmahon/MIT_projects/unplatform_v2
11 silly lifecycle Unplatform-V2@1.2.0~compile:ui: Args: [ '-c',
11 silly lifecycle   'cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/' ]
12 silly lifecycle Unplatform-V2@1.2.0~compile:ui: Returned: code: 64  signal: null
13 info lifecycle Unplatform-V2@1.2.0~compile:ui: Failed to exec compile:ui script
14 verbose stack Error: Unplatform-V2@1.2.0 compile:ui: `cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/`
14 verbose stack Exit status 64
14 verbose stack     at EventEmitter.<anonymous> (/Users/kathleenmcmahon/.virtualenvs/venv/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/kathleenmcmahon/.virtualenvs/venv/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Unplatform-V2@1.2.0
16 verbose cwd /Users/kathleenmcmahon/MIT_projects/unplatform_v2
17 error Darwin 16.4.0
18 error argv "/Users/kathleenmcmahon/.virtualenvs/venv/bin/node" "/Users/kathleenmcmahon/.virtualenvs/venv/bin/npm" "run" "compile:ui"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error Unplatform-V2@1.2.0 compile:ui: `cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/`
22 error Exit status 64
23 error Failed at the Unplatform-V2@1.2.0 compile:ui script 'cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Unplatform-V2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Unplatform-V2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Unplatform-V2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by resource11** [comment]
Found yarn.lock file in ui folder, tried running yarn instead of npm install. Code had much more success in compiling then ultimately failed:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/kathleenmcmahon/.virtualenvs/venv/bin/node',
1 verbose cli   '/Users/kathleenmcmahon/.virtualenvs/venv/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile:ui' ]
2 info using npm@4.1.2
3 info using node@v7.5.0
4 verbose run-script [ 'precompile:ui', 'compile:ui', 'postcompile:ui' ]
5 info lifecycle Unplatform-V2@1.2.0~precompile:ui: Unplatform-V2@1.2.0
6 silly lifecycle Unplatform-V2@1.2.0~precompile:ui: no script for precompile:ui, continuing
7 info lifecycle Unplatform-V2@1.2.0~compile:ui: Unplatform-V2@1.2.0
8 verbose lifecycle Unplatform-V2@1.2.0~compile:ui: unsafe-perm in lifecycle true
9 verbose lifecycle Unplatform-V2@1.2.0~compile:ui: PATH: /Users/kathleenmcmahon/.virtualenvs/venv/lib/node_modules/npm/bin/node-gyp-bin:/Users/kathleenmcmahon/MIT_projects/unplatform_v2/node_modules/.bin:/Users/kathleenmcmahon/.virtualenvs/venv/bin:/Users/kathleenmcmahon/.nvm/versions/node/v6.9.4/bin:/usr/local/Cellar/pyenv-virtualenv/20160315/shims:/usr/local/var/pyenv/shims:/usr/local/var/rbenv/shims:/Users/kathleenmcmahon/.rbenv/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle Unplatform-V2@1.2.0~compile:ui: CWD: /Users/kathleenmcmahon/MIT_projects/unplatform_v2
11 silly lifecycle Unplatform-V2@1.2.0~compile:ui: Args: [ '-c',
11 silly lifecycle   'cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/' ]
12 silly lifecycle Unplatform-V2@1.2.0~compile:ui: Returned: code: 64  signal: null
13 info lifecycle Unplatform-V2@1.2.0~compile:ui: Failed to exec compile:ui script
14 verbose stack Error: Unplatform-V2@1.2.0 compile:ui: `cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/`
14 verbose stack Exit status 64
14 verbose stack     at EventEmitter.<anonymous> (/Users/kathleenmcmahon/.virtualenvs/venv/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/kathleenmcmahon/.virtualenvs/venv/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Unplatform-V2@1.2.0
16 verbose cwd /Users/kathleenmcmahon/MIT_projects/unplatform_v2
17 error Darwin 16.4.0
18 error argv "/Users/kathleenmcmahon/.virtualenvs/venv/bin/node" "/Users/kathleenmcmahon/.virtualenvs/venv/bin/npm" "run" "compile:ui"
19 error node v7.5.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error Unplatform-V2@1.2.0 compile:ui: `cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/`
22 error Exit status 64
23 error Failed at the Unplatform-V2@1.2.0 compile:ui script 'cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Unplatform-V2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     cd ui && npm install  && rm -rf dist/ && npm run compile:prod && cp -rf dist/* ../static/ui/
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Unplatform-V2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Unplatform-V2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
